{% set AS_version="0.1546.1" %}
{% set AA_version="1.3.r5" %}
{% set AC_version="0.5.2" %}

package:
    name: ampliconsuite
    version: {{ AS_version }}

source:
    - url: https://github.com/AmpliconSuite/AmpliconSuite-pipeline/archive/v{{ AS_version }}.tar.gz
      sha256: 129a2606a7e66168925784205a75ff6134c2280e2379ee523375ea6aa3a384f3
    - url: https://github.com/AmpliconSuite/AmpliconArchitect/archive/v{{ AA_version }}.tar.gz
      sha256: f103223da49901ef0d04d0886ed8ea86f23067df93b15424c5af6a95850f3777
      folder: ampliconarchitectlib
    - url: https://github.com/AmpliconSuite/AmpliconClassifier/archive/v{{ AC_version }}.tar.gz
      sha256: 938ba57d4e2a02eeb12787bf70df4e616561e7a73c46bc947214087f2325c380
      folder: ampliconclassifierlib

build:
    noarch: python
    number: 0

requirements:
    build:
        - python >=3
        - setuptools
        - unzip
        - wget

    run:
        - python >=3
        - bwa
        - cnvkit
        - Flask
        - future >=0.18.3
        - intervaltree
        - matplotlib-base >=3.5.1
        - mscorefonts
        - numpy >=1.22.4
        - pysam
        - samtools
        - scipy >=1.7.3

test:
    commands:
    - AmpliconSuite-pipeline.py -v
    imports:
    - paalib
    - ampliconarchitectlib
    - ampliconclassifierlib

about:
    home: https://github.com/AmpliconSuite
    license: BSD 2-Clause License
    summary: An end-to-end wrapper for focal amplification analysis from whole-genome sequencing using AmpliconArchitect and associated tools.
